### ISSUE TITLE
[inversify-binding-decorators autoProvide is not work]Error: No matching bindings found for serviceIdentifier: Katana

### ISSUE THREAD

**Issue by LincWong** [inversify/InversifyJS#1164]
autoProvide demo can't work

## Expected Behavior
```
Using Katana...
```

## Current Behavior
```shell
/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/planning/planner.js:145
        throw error;
        ^

Error: No matching bindings found for serviceIdentifier: Warrior
    at _validateActiveBindingCount (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/planning/planner.js:62:23)
    at _getActiveBindings (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/planning/planner.js:48:5)
    at _createSubRequests (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/planning/planner.js:85:26)
    at Object.plan (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/planning/planner.js:136:9)
    at /Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/container/container.js:317:37
    at Container._get (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/container/container.js:310:44)
    at Container.get (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/container/container.js:230:21)
    at Object.<anonymous> (/Users/huangzhipeng/Documents/work/linchuang/ts/dist/ioc/index.js:9:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

## Possible Solution
:(

## Steps to Reproduce (for bugs)
demo link: https://codesandbox.io/embed/epic-bash-zrdmo

## Context
just autoProvide Demo

## Your Environment

* Version used: 
```
"inversify": "^5.0.1",
"inversify-binding-decorators": "^4.0.0",
"reflect-metadata": "^0.1.13",
"typescript": "^3.6.3"
```
* Environment name and version: nodeJS v10.11.0
* Link to your project:

# Stack trace
```shell
/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/planning/planner.js:145
        throw error;
        ^

Error: No matching bindings found for serviceIdentifier: Warrior
    at _validateActiveBindingCount (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/planning/planner.js:62:23)
    at _getActiveBindings (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/planning/planner.js:48:5)
    at _createSubRequests (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/planning/planner.js:85:26)
    at Object.plan (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/planning/planner.js:136:9)
    at /Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/container/container.js:317:37
    at Container._get (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/container/container.js:310:44)
    at Container.get (/Users/huangzhipeng/Documents/work/linchuang/ts/node_modules/inversify/lib/container/container.js:230:21)
    at Object.<anonymous> (/Users/huangzhipeng/Documents/work/linchuang/ts/dist/ioc/index.js:9:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by LincWong** [comment]
@remojansen
