### ISSUE TITLE
Lazy injection on static property crashes

### ISSUE THREAD

**Issue by Wgil** [inversify/InversifyJS#1248]
## Expected Behavior

Lazy injection should inject static properties

## Current Behavior

Getting a `TypeError: Cannot read property 'get' of undefined` after trying to access to the static property.

## Steps to Reproduce (for bugs)
This is my current code:
```ts
const { lazyInject } = getDecorators(container)

export class View  {
  @lazyInject(TYPES.RequestContext)
  public static __ctx: IRequestContext

  // FACTORY METHOD
  static async create(data: Data) {
    console.log(View.__ctx) // crashes
    return new View()
  }

  private constructor() {
    // Irrelevant stuff here
  }
}
```

# Stack trace

```
stack: "TypeError: Cannot read property 'get' of undefined\n" +
    '    at resolve (/Users/warao/Projects/backend-core/node_modules/inversify-inject-decorators/lib/decorators.js:30:34)\n' +
    '    at Function.getter [as __ctx] (/Users/warao/Projects/backend-core/node_modules/inversify-inject-decorators/lib/decorators.js:7:47)\n' +
    '    at Function.create (/Users/warao/Projects/backend-core/src/components/view/domain/View.ts:44:26)\n' +
```

Any help would be appreciated

**Comment by Wgil** [comment]
Closing this, I was having a circular dependency
