### ISSUE TITLE
Nested dependency is undefined (after being injected correctly???)

### ISSUE THREAD

**Issue by y-chen** [inversify/InversifyJS#1259]
## Summary
Using property injection, only direct property has been valorised. This property has another dependency that is undefined.

**EDIT**
I'm still trying to find out what is the problem. Now I tried to inject the undefined class into the constructor and something strange happens: InversifyJS injects the dependency correctly, I assign it to the property but it's undefined when I try to use it.

```
   interface ICitiesRepo { /* interface members */ }

   @injectable()
   class CitiesRepo implements ICitiesRepo {
       private readonly repo: IWriteRepo<City>;

       constructor(@inject('CitiesWriteRepo') repo: IWriteRepo<City>) {
          console.log(repo); // result: WriteRepo {}
          this.repo = repo;
          console.log(this.repo); // result: WriteRepo {}
       }

       getAll() {
          console.log(this.repo); // result: undefined
       }

       // interface implementation
   }
```

## Expected Behavior
All dependencies are valorised.

## Current Behavior
Only the first level dependency has been injected

## Possible Solution
//

## Steps to Reproduce (for bugs)
[Some more details](https://stackoverflow.com/questions/64683100/inversifyjs-nested-dependency-is-undefined)

## Context
Trying to inject all dependencies in a generic repository pattern

## Your Environment
//

# Stack trace
```
(node:91669) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ensureQueryRunner' of undefined
    at Object.<anonymous> (/Users/<user>/Documents/GitHub/<project>/dist/apps/tester/webpack:/libs/repo/src/repo/cities.repo.ts:31:25)
    at Generator.next (<anonymous>)
    at /Users/<user>/Documents/GitHub/<project>/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/<user>/Documents/GitHub/<project>/node_modules/tslib/tslib.js:111:16)
    at Object.ensureDb (/Users/<user>/Documents/GitHub/<project>/dist/apps/tester/main.js:556:24)
    at /Users/<user>/Documents/GitHub/<project>/dist/apps/tester/webpack:/libs/repo/src/decorators/ensureDb.ts:9:40
    at Generator.next (<anonymous>)
    at /Users/<user>/Documents/GitHub/<project>/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
(node:91669) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:91669) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by y-chen** [comment]
My issue is not really related to inversify, I will close it.
You can check the [link](https://stackoverflow.com/questions/64683100/decorator-to-call-a-method-before-any-other-messes-with-this-context) if you want to know the real problem.
