### ISSUE TITLE
Error trying to instantiate controller in a test (extending BaseHttpController, using inversify-express-utils)

### ISSUE THREAD

**Issue by marcosdipaoloSV** [inversify/InversifyJS#1289]
## Expected Behavior
I'm trying to write a unit test  for a controller that has an injected service at the constructor. The controller extends the `BaseHttpController` from ` inversify-express-utils` I'm failing trying to  do:
```typescript
import { expect } from "chai"
import { container } from '../../src/container/inversify.config'
import { HealthControllerV1 } from "../../src/controllers/v1/HealthControllerV1"
import { results } from "inversify-express-utils"

describe("ExampleController", () => {
    let controller: HealthControllerV1

    beforeEach(() => {
        controller = container.get<HealthControllerV1>(HealthControllerV1)
    })

    describe("Health", () => {
        it("should return 200 status with Json response", async () => {
            const response = controller.health()
            expect(response).to.be.an.instanceof(results.JsonResult)
        })
    })
})  
```
I think it should be able to instantiate it through the container but instead i get:
```bash
HealthControllerV1
    Health
      1) "before each" hook for "should return 200 status with Json response"


  0 passing (8ms)
  1 failing

  1) HealthControllerV1
       "before each" hook for "should return 200 status with Json response":
     Error: No matching bindings found for serviceIdentifier: Symbol(HttpContext)
 ```

## Your Environment
```json
"inversify": "^5.0.5",
"inversify-express-utils": "^6.3.2",
"node": "12.20.0"
"chai": "^4.3.0",
"express": "^4.17.1",
"mocha": "^8.3.0",
"reflect-metadata": "^0.1.13",
```
# Stack trace
```bash
 Error: No matching bindings found for serviceIdentifier: Symbol(HttpContext)
      at _validateActiveBindingCount (node_modules/inversify/lib/planning/planner.js:63:23)
      at _getActiveBindings (node_modules/inversify/lib/planning/planner.js:49:5)
      at _createSubRequests (node_modules/inversify/lib/planning/planner.js:92:26)
      at /home/marcosdipaolo/Documents/dev/goals-backend/node_modules/inversify/lib/planning/planner.js:116:17
      at Array.forEach (<anonymous>)
      at /home/marcosdipaolo/Documents/dev/goals-backend/node_modules/inversify/lib/planning/planner.js:115:26
      at Array.forEach (<anonymous>)
      at _createSubRequests (node_modules/inversify/lib/planning/planner.js:95:20)
      at Object.plan (node_modules/inversify/lib/planning/planner.js:137:9)
      at /home/marcosdipaolo/Documents/dev/goals-backend/node_modules/inversify/lib/container/container.js:319:37
      at Container._get (node_modules/inversify/lib/container/container.js:312:44)
      at Container.get (node_modules/inversify/lib/container/container.js:232:21)
      at Context.<anonymous> (test/unit/health.test.ts:10:32)
      at processImmediate (internal/timers.js:461:21)
```

thanks a lot

**Comment by marcosdipaoloSV** [comment]
For some reason i neither know nor understand, in a test you need to mock the httpContext (the one you get from BaseHttpController) and bind it to the container before you try to instantiate the controller

The mocked httpContext
```typescript
import { mockReq, mockRes } from 'sinon-express-mock'
import { interfaces } from "inversify-express-utils"
import { container } from '../src/container/inversify.config'

const mockRequest = mockReq()
const mockResponse = mockRes()

const mockUser: interfaces.Principal = {
    details: "",
    isAuthenticated: () => Promise.resolve(true),
    isResourceOwner: () => Promise.resolve(true),
    isInRole: () => Promise.resolve(true)
}

export const mockedHttpContext: interfaces.HttpContext = {
    request: mockRequest,
    response: mockResponse,
    user: mockUser,
    container
}
```
The test
```typescript
import { expect } from "chai"
import { container } from '../../src/container/inversify.config'
import { HealthControllerV1 } from "../../src/controllers/v1/HealthControllerV1"
import { results, interfaces } from "inversify-express-utils"
import { mockedHttpContext } from '../mockedHttpContext'

describe("HealthControllerV1", () => {
    let controller: HealthControllerV1
    
    container.bind<interfaces.HttpContext>(Symbol.for("HttpContext")).toConstantValue(mockedHttpContext)
    
    beforeEach(() => {
        controller = container.get<HealthControllerV1>(HealthControllerV1)
    })

    describe("Health", () => {
        it("should return 200 status with Json response", async () => {
            const response = controller.health()
            expect(response).to.be.an.instanceof(results.JsonResult)
        })
    })
})      
```
