### ISSUE TITLE
[Firebase Cloud Functions] TypeError: Cannot convert a Symbol value to a number

### ISSUE THREAD

**Issue by tperraut** [inversify/InversifyJS#1364]
After following the get started of inversify, I added a first injection to my project but I am struggling as I am getting the error : `TypeError: Cannot convert a Symbol value to a number` and if I change symbols for normal string the service I use does not seem to be injected properly as I am getting `TypeError: myInjectedService.doSomething is not a function`

## Expected Behavior
I am expecting Symbol to work as is on node 12 and injection to be done as expected while following the setup guide

## Current Behavior
Symbol seem to be mixed with number internally causing a `TypeError` and injection seems not to ne done properly

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
Here is what I have : 

```typescript
// Config.ts
export interface Config {
  x: boolean
}

// IZoneService.ts
export interface IZoneService {
  doSomething(): void
}

// inversify.config.ts
import {TYPES} from "./Types";
import {Container} from "inversify";
import {Config} from "../models/Config";
import {ZoneService} from "../services/zones/ZoneService";
import {IZoneService} from "../services/interfaces/IZoneService";

const DI = new Container()
DI.bind<Config>(TYPES.Config).toConstantValue({x: true} as Config)
DI.bind<IZoneService>(TYPES.ZoneService).to(ZoneService).inSingletonScope()

export {DI}

// Types.ts
import "reflect-metadata";

export const TYPES = {
  Config: Symbol.for("Config"),
  ZoneService: Symbol.for("ZoneService"),
}

// ZoneService.ts
import {TYPES} from "../../di/Types";
import {inject, injectable} from "inversify";
import {Config} from "../../models/Config";
import {IZoneService} from "../interfaces/IZoneService";

@injectable()
class ZoneService implements IZoneService {

  public constructor(
    @inject(TYPES.Config) config: Config
  ) {
    ...
  }
  ...
  public doSomething(): void {
    ...
  }
}

// ZoneInteractor.js
const {DI} = require("../di/inversify.config");
const {IZoneService} = require("../services/interfaces/IZoneService");
const {TYPES} = require("../di/Types");

class ZoneInteractor {
  async run() {
    ...
    const zoneService = DI.get<IZoneService>(TYPES.ZoneService) // Issue 1
    zoneService.doSomething() // Issue 2
  }
}
```
**Issue 1 :** I am getting `Cannot convert a Symbol value to a number` on the line.

If I change `TYPES` object for `string` only like this :
```typescript
export const TYPES = {
  Config: "Config",
  ZoneService: "ZoneService",
}
```
I am getting the second issue,
**Issue 2 :** `TypeError: zoneService.doSomething is not a function`

## Context
I am trying to simply inject some service by following the Inversify setup

## Your Environment

* Version used: inversify 5.1.1 / reflect-metadata 0.1.13
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs 12
* Operating System and version (desktop or mobile): firebase cloud function container
* Link to your project: private

# Stack trace
**Issue 1 :**
```
TypeError: Cannot convert a Symbol value to a number
    at RedZoneInteractor.run (/workspace/lib/interactors/zoneInteractor.js:36:51)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
```
**Issue 2:**
```
TypeError: zoneService.doSomething is not a function
    at RedZoneInteractor.run (/workspace/lib/interactors/zoneInteractor.js:37:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
```

Thank you for your work.

**Comment by tperraut** [comment]
God, it was just the type in a `.js` file for the line `DI.get<IZoneService>(TYPES.ZoneService)` breaking everything...
