### ISSUE TITLE
False positive: Derived class must explicitly declare its constructor.

### ISSUE THREAD

**Issue by hourliert** [inversify/InversifyJS#168]
Hi,

Since https://github.com/inversify/InversifyJS/pull/158, I have a false positive when the base class doesn't use DI and the derieved class does.
## Expected Behavior

We should be able to extend class that doesn't use DI (and is not annotated by `@injectable()`) to create a new class that is `@injectable()` and uses DI.
## Current Behavior

The following snippet doesn't work:

**Base Class:**

``` ts
class Store<T> {
  constructor(
    private _config: T
  ) {}
}
```

**Derived Class:**

``` ts
@injectable()
class ServerStore extends Store<IServer> {
  constructor() {
    super({ name: 'C9000-AWS' });
  }
}
```

When I `@inject()` `ServerStore`, I have this error:
`Error: Derived class must explicitly declare its constructor: ServerStore.`
## Possible Solution

We should reinforce [this condition](https://github.com/remojansen/InversifyJS/blob/master/src/planning/planner.ts#L222).

I have a lot of work right now. But I guess I will be able to fix this Monday or Tuesday?
## Steps to Reproduce (for bugs)

Check the previous snippet.
## Your Environment
- Version used: **beta.1**
# Stack trace

```
Error: Derived class must explicitly declare its constructor: ServerStore.
    at Planner._createSubRequest (/Users/thomashourlier/Projects/react/retax/node_modules/inversify/lib/planning/planner.js:73:23)
    at /Users/thomashourlier/Projects/react/retax/node_modules/inversify/lib/planning/planner.js:27:60
    at Array.forEach (native)
    at Planner.createPlan (/Users/thomashourlier/Projects/react/retax/node_modules/inversify/lib/planning/planner.js:27:22)
    at Kernel._planAndResolve (/Users/thomashourlier/Projects/react/retax/node_modules/inversify/lib/kernel/kernel.js:116:23)
    at Kernel._get (/Users/thomashourlier/Projects/react/retax/node_modules/inversify/lib/kernel/kernel.js:108:25)
    at Kernel.get (/Users/thomashourlier/Projects/react/retax/node_modules/inversify/lib/kernel/kernel.js:60:21)
    at Object.<anonymous> (/source/src/index.ts:20:39)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by remojansen** [comment]
Hi @hourliert thanks for reporting this. I have assigned the issue to you. Send a PR whenever you have a chance, no need to be in a hurry :wink:
