### ISSUE TITLE
Unexpected token exception when injected interface has method with rest parameters (... arguments)

### ISSUE THREAD

**Issue by zkohl** [inversify/InversifyJS#188]
## Expected Behavior

Inversify should be able to bind interface that has method with rest parameters.
## Current Behavior

Exception is thrown with message "Unexpected token ..."
## Steps to Reproduce (for bugs)

import {injectable} from "inversify";

export interface ITest{
    run(msg : string, ...meta: any[]);
}

@injectable()
export class Test implements ITest {
    run(msg : string, ...meta: any[]) {
        console.log(msg, ...any);
    }
}

let kernel = new Kernel();

kernel.bind<ITest>("ITest").to(Test);
## Context

I was trying to create an interface for a logger. A simple example is wrapping console.log(msg: string, meta: any[])
## Your Environment

- Version used: 2.0.0-beta2
- Environment name and version: Node.js v4.4.2
- Operating System and version (desktop or mobile): Mac OS X 10.11.4
- Link to your project:
# Stack trace

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/zkohl/Code/swat-server/build/config/container.js:2:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/zkohl/Code/swat-server/build/services/database.js:3:21)
    at Module._compile (module.js:409:26)

**Comment by zkohl** [comment]
This appears to be a limitation of Node. So not a problem with Inversify :)

https://github.com/Microsoft/TypeScript/issues/6740

Thanks for all your hard work!

**Comment by remojansen** [comment]
No worries, thanks for using the library :+1:
