### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by ghost** [inversify/InversifyJS#267]
## Expected Behavior

Something in the lines of:

```
Error: no binding found for symbol
```
## Current Behavior

```
TypeError: Cannot convert a Symbol value to a string
```
## Possible Solution

It seems that there is no neat way to get the string representation of a symbol, so just throwing `Error: no binding found for symbol` seems to be the best solution (if I'm correct). There is `Symbol.keyFor`, but that only works if the symbol was a global symbol.
## Steps to Reproduce

Just `kernel.get()` with a symbol that is not registered.
## Context

I am building [an app development platform](http://github.com/comet-platform) and accompanying [application runtime](http://github.com/comet-platform/comet-runtime) that relies on Inversify to do the heavy work. I hope one day (in the distant future) to use this platform to build a  [CMS](http://github.com/EngageJS).

I also wanted to take this occasion to tank you for you awesome contributions and I really hope this project will continue to grow. It is not often that I see a project this well-made.
## Your Environment

- Version used: 2.0.0-beta.10
- Environment name and version: NodeJS v5.11.0
- Operating System and version (desktop or mobile): OS X El Capitan
- Link to your project: http://github.com/comet-platform/comet-runtime
# Stack trace

```
TypeError: Cannot convert a Symbol value to a string
    at Kernel._getActiveBindings (/Users/samvv/Projects/node/comet-runtime/node_modules/inversify/lib/kernel/kernel.js:169:65)
    at Kernel._plan (/Users/samvv/Projects/node/comet-runtime/node_modules/inversify/lib/kernel/kernel.js:186:29)
    at Kernel._planAndResolve (/Users/samvv/Projects/node/comet-runtime/node_modules/inversify/lib/kernel/kernel.js:157:29)
    at Kernel._get (/Users/samvv/Projects/node/comet-runtime/node_modules/inversify/lib/kernel/kernel.js:149:27)
    at Kernel.get (/Users/samvv/Projects/node/comet-runtime/node_modules/inversify/lib/kernel/kernel.js:80:21)
    at Object.<anonymous> (/Users/samvv/Projects/node/comet-runtime/test.js:23:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by remojansen** [comment]
Hi thanks a lot for reporting this issue. I've been able to [fix it and it is now merged into master](https://github.com/inversify/InversifyJS/pull/270). It will be included in the next release.
