### ISSUE TITLE
Build issue "MongoDBClient "before all" hook"

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#280]
```
1) MongoDBClient "before all" hook:
     Uncaught TypeError: Cannot read property 'collection' of null
      at ../../../../../MongoDB/test/utils/mongodb/client.spec.ts:14:9
      at C:\projects\inversify-express-example\node_modules\mongodb\lib\mongo_client.js:330:20
      at C:\projects\inversify-express-example\node_modules\mongodb\lib\db.js:231:14
      at .<anonymous> (C:\projects\inversify-express-example\node_modules\mongodb\lib\server.js:240:9)
      at .<anonymous> (C:\projects\inversify-express-example\node_modules\mongodb-core\lib\topologies\server.js:218:12)
      at .<anonymous> (C:\projects\inversify-express-example\node_modules\mongodb-core\lib\connection\pool.js:119:12)
      at Socket.<anonymous> (C:\projects\inversify-express-example\node_modules\mongodb-core\lib\connection\connection.js:151:49)
      at emitErrorNT (net.js:1272:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by lholznagel** [comment]
Oh I think I now what is wrong. Need to change the config so that I have a running mongodb.

Travis actually fails with `The command "npm typings install" failed and exited with 1 during .` think that I am missing a `-g` in the install script. Will take a look at it tomorrow

**Comment by remojansen** [comment]
I see a different problem [here](https://ci.appveyor.com/project/remojansen/inversify-express-example/build/3/job/utrdgq1b1u9gbfp2#L658) and [here](https://travis-ci.org/inversify/inversify-express-example/jobs/140815076#L793-L804).

**Comment by lholznagel** [comment]
Fixed with inversify/inversify-express-example#7

**Comment by lholznagel** [comment]
This can be closed. Both appveyor and travis are completely successful

**Comment by remojansen** [comment]
:+1:
