### ISSUE TITLE
Crash: getTagged + multi injection

### ISSUE THREAD

**Issue by Offirmo** [inversify/InversifyJS#345]
I tried the following construct:

``` js
kernel
    .bind<IIntl>('intl')
    .toConstantValue({
        hello: 'bonjour'
    })
    .whenTargetTagged('lang', 'fr')
kernel
    .bind<IIntl>('intl')
    .toConstantValue({
        goodbye: 'au revoir'
    })
    .whenTargetTagged('lang', 'fr')

console.log(kernel.getTagged<IIntl>('intl', 'lang', 'fr'))
```
## Expected Behavior

Not crashing.
## Current Behavior

```
node_modules/inversify/lib/utils/utils.js:9
    return f.name ? f.name : f.toString().match(/^function\s*([^\s(]+)/)[1];
            ^
TypeError: Cannot read property 'name' of null
```
## Possible Solution

?
## Steps to Reproduce (for bugs)

Code given above +

```
interface IIntl {
    [k: string]: string
}
```
## Context

trying to use inversify for declaring intl fragments
## Your Environment
- Version used:
- node 6.4, inversify 2 rc10, typescript 2.1.0-dev.20160822
- Ubuntu 16
# Stack trace

```
node_modules/inversify/lib/utils/utils.js:9
    return f.name ? f.name : f.toString().match(/^function\s*([^\s(]+)/)[1];
            ^
TypeError: Cannot read property 'name' of null
    at Object.getFunctionName (web-tech-experiments/node_modules/inversify/lib/utils/utils.js:9:13)
    at web-tech-experiments/node_modules/inversify/lib/kernel/kernel.js:227:83
    at Array.forEach (native)
    at Kernel._listRegisteredBindingsForServiceIdentifier (web-tech-experiments/node_modules/inversify/lib/kernel/kernel.js:226:32)
    at Kernel._getActiveBindings (web-tech-experiments/node_modules/inversify/lib/kernel/kernel.js:194:35)
    at Kernel._plan (web-tech-experiments/node_modules/inversify/lib/kernel/kernel.js:204:29)
    at Kernel._planAndResolve (web-tech-experiments/node_modules/inversify/lib/kernel/kernel.js:165:29)
    at Kernel._get (web-tech-experiments/node_modules/inversify/lib/kernel/kernel.js:157:27)
    at Kernel.getTagged (web-tech-experiments/node_modules/inversify/lib/kernel/kernel.js:94:21)
    at Object.<anonymous> (web-tech-experiments/typescript/mod_inversify_004_tagged/index.ts:66:20)
```

**Comment by remojansen** [comment]
There was a bug which prevented the following error to be displayed. The error is:

``` ts
Error: Ambiguous match found for serviceIdentifier: Intl
Registered bindings:
 Object - tagged: { key:lang, value: fr }
 Object - tagged: { key:lang, value: fr }
```

I have created a [PR](https://github.com/inversify/InversifyJS/pull/347) that will be merged soon and I will do a release ASAP.

We don't have a feature at the moment to get multiple results with a tag. We need something like `getAllTagged` and `getAllNamed` I'm going to take note and this is something that could be implemented in the future. For the moment you can do the following:

``` ts
kernel.bind<Intl>("Intl").toConstantValue({ lang: "fr", hello: "bonjour" });
kernel.bind<Intl>("Intl").toConstantValue({ lang: "fr", goodbye: "au revoir" });

kernel.bind<Intl>("Intl").toConstantValue({ lang: "es", hello: "hola" });
kernel.bind<Intl>("Intl").toConstantValue({ lang: "es", goodbye: "adios" });

function getLang(lang) {
    return kernel.getAll<Intl>("Intl").filter((i) => { return i.lang === lang})
}

let fr = getLang("fr");
let es = getLang("es");
```

**Comment by Offirmo** [comment]
@remojansen thanks !

The idea would be to use a provider for lazy-loading languages on-demand. I'm definitely interested in `getAllTagged` and `getAllNamed` !

For now, I'm including the lang in the Service Id instead `kernel.bind<Intl>("Intl.fr")` and using `getAll`

**Comment by Offirmo** [comment]
@remojansen opened a new issue for the feature request https://github.com/inversify/InversifyJS/issues/348

**Comment by remojansen** [comment]
@Offirmo thanks for the feature request I will work on that ASAP 😄

**Comment by Offirmo** [comment]
@remojansen you are amazing
