### ISSUE TITLE
The number of constructor arguments in the derived class UserModelRepository must be >= than the number of constructor arguments of its base class.

### ISSUE THREAD

**Issue by simon-hardy** [inversify/InversifyJS#372]
## Expected Behavior

Constructor of base class and derived class both have 3 arguments, this should be OK.
## Current Behavior

Error message is shown.
## Steps to Reproduce (for bugs)
1. Base class constructor:

``` ts
@injectable()
export default class TemplateViewModelRepository<TModel>
{
    constructor(
        host: RethinkDb.ConnectionOptions,
        dbName: string,
        tableName: string)
    {`
```
1. Derived class:

``` ts
@injectable()
export default class UserModelRepository extends TemplateViewModelRepository<User> implements IReadUserModels, IWriteUserModels
{
    constructor(
        @inject('RethinkDb.ConnectionOptions') host: RethinkDb.ConnectionOptions,
        @inject('string') dbName: string = 'ViewModels',
        @inject('string') tableName: string = 'Users')
    {
        super(host, dbName, tableName);
    }
```
## Your Environment
- Version used: "inversify": "^2.0.0"
- Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs 6.5.0
- Operating System and version (desktop or mobile): Mac OSX
# Stack trace

``` ts
Error: The number of constructor arguments in the derived class UserModelRepository must be >= than the number of constructor arguments of its base class.\n    
at Planner._createSubRequest (/Users/simon/code/njar/njarservices/node_modules/inversify/lib/planning/planner.js:74:23)\n
at /Users/simon/code/njar/njarservices/node_modules/inversify/lib/planning/planner.js:24:64\n 
at Array.forEach (native)\n    at Planner.createPlan (/Users/simon/code/njar/njarservices/node_modules/inversify/lib/planning/planner.js:24:26)\n    
at Kernel._createContext (/Users/simon/code/njar/njarservices/node_modules/inversify/lib/kernel/kernel.js:220:23)\n   
at /Users/simon/code/njar/njarservices/node_modules/inversify/lib/kernel/kernel.js:214:26\n   
at Array.map (native)\n    at Kernel._plan (/Users/simon/code/njar/njarservices/node_modules/inversify/lib/kernel/kernel.js:213:33)\n   
at Kernel._planAndResolve (/Users/simon/code/njar/njarservices/node_modules/inversify/lib/kernel/kernel.js:173:29)\n    
at Kernel._get (/Users/simon/code/njar/njarservices/node_modules/inversify/lib/kernel/kernel.js:165:27)\n   
at Kernel.get (/Users/simon/code/njar/njarservices/node_modules/inversify/lib/kernel/kernel.js:76:21)\n    at Function.Register (/Users/simon/code/njar/njarservices/build/src/App_Code/Users/UserEventHandling.js:8:44)\n    
at Function.BootUsers (/Users/simon/code/njar/njarservices/build/src/App_Start/Bootstrapper.js:83:37)\n    
at Function.Boot (/Users/simon/code/njar/njarservices/build/src/App_Start/Bootstrapper.js:25:34)\n    
at Object.<anonymous> (/Users/simon/code/njar/njarservices/build/src/App.js:8:40)\n    
at Module._compile (module.js:556:32)
```

**Comment by remojansen** [comment]
Sorry but optional dependencies are not supported:

``` ts
constructor(
        @inject('RethinkDb.ConnectionOptions') host: RethinkDb.ConnectionOptions,
        @inject('string') dbName: string = 'ViewModels', // optional NOT SUPPORTED!
        @inject('string') tableName: string = 'Users' // optional NOT SUPPORTED!
) {
// ...
```

You need to use the `@unmanaged` decorator:

``` ts
import { inject, unmanaged, injectable } from "inversify";

@injectable()
export default class TemplateViewModelRepository<TModel>
{
    public host: RethinkDb.ConnectionOptions;
    public dbName: string;
    public tableName: string;

    constructor(
        @inject("RethinkDb.ConnectionOptions") host: RethinkDb.ConnectionOptions,
        @unmanaged() dbName: string,
        @unmanaged() tableName: string
    ) {
        this.host = host;
        this.dbName= dbName;
        this.tableName= tableName;
    }
}

@injectable()
export default class UserModelRepository 
    extends TemplateViewModelRepository<User> implements IReadUserModels, IWriteUserModels {
    constructor(
        @inject('RethinkDb.ConnectionOptions') host: RethinkDb.ConnectionOptions
    ) {
        super(host, "ViewModels", "Users");
    }
}
```

You can find the documentation about it [here](https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md).

Please let me know if this solves your issue and I will close it.

**Comment by simon-hardy** [comment]
Ah brilliant, thanks.

**Comment by frossi85** [comment]
Sorry to revive an old issue, but how I can do the same in ES6??

**Comment by remojansen** [comment]
@frossi85 you need to use the [`decorate` helper](https://github.com/inversify/InversifyJS/blob/master/wiki/javascript.md#inversify-with-es6).

For property decorators you need something like:
```ts
lazyInject(TYPES.SomeDependency)(MyComponent.prototype, "_someProperty");
```
Which is the same as:

```ts
class Something {
   @lazyInject(TYPES.SomeDependency) private _someProperty: any;
   // ...
}
```
