### ISSUE TITLE
Binding parameters sanity validation

### ISSUE THREAD

**Issue by IdeaHunter** [inversify/InversifyJS#457]
I occasionally passed wrong parameter type (string) for `toSelf` binding and got error with no message only after trying to instantiate it

## Expected Behavior
Throw an error/emit compilation error when calling `toSelf`

## Current Behavior
An error with no message (see callstacks below)

## Possible Solution
Add some soft of foolproofness for input parameters with meaningful error message - or maybe find a way to restrict things at compilation level - since there also issue with _de facto_ argument **type**

## Steps to Reproduce (for bugs)
```js
import "reflect-metadata"
import { Container } from 'inversify'
let container = new Container()
container.bind('testId').toSelf()
let service = container.get('testId')
```
## Context
Im using helper function to dynamically create child container with different set of dependencies to instantiate class with it and also to abstract out of inversify itself
```js
function create<T>(ctx: interfaces.Context, type: interfaces.ServiceIdentifier<any>, args: { [name: string]: any }): IPromise<T> {
    if (!args)
        return ctx.container.get(type)

    let innerKernel = new Container()
    innerKernel.parent = ctx.container
    _.each(args, (val, key) => {
        if (typeof val === 'function') {
            innerKernel.bind(key).to(val)
        } else {
            innerKernel.bind(key).toConstantValue(val)
        }
    })
    // this line lead me to an error - it got removed right after the bug appear
    innerKernel.bind(type).toSelf()
    return innerKernel.get(type)
}

childKernel.bind('create').toDynamicValue(ctx => function createSubContainerDi(type, args) {
    if (type === 'create')
        return (type, args) => create(ctx, type, args)
    else
        return create(ctx, type, args)
})
```

## Your Environment
* Version used: 3.0.0-rc.2, (reflect-metadata: 0.1.9) 
* Environment name and version: node v7.2.1
* Operating System and version (desktop or mobile):  Debian GNU/Linux testing (stretch), desktop
* Link to your project: its private

# Stack trace
1) Rethrown stacktrace
```
Error,
    at _createSubRequests (/home/igor/psb/node_modules/inversify/lib/planning/planner.js:106:19)
    at Object.plan (/home/igor/psb/node_modules/inversify/lib/planning/planner.js:125:5)
    at /home/igor/psb/node_modules/inversify/lib/container/container.js:191:37
    at Container._get (/home/igor/psb/node_modules/inversify/lib/container/container.js:184:44)
    at Container.get (/home/igor/psb/node_modules/inversify/lib/container/container.js:149:21)
```
2) Full stack trace
```
TypeError
    at Object.getMetadata (/home/igor/psb/node_modules/reflect-metadata/Reflect.ts:704:38)
    at getTargets (/home/igor/psb/node_modules/inversify/lib/planning/reflection_utils.js:21:38)
    at Object.getDependencies (/home/igor/psb/node_modules/inversify/lib/planning/reflection_utils.js:9:19)
    at /home/igor/psb/node_modules/inversify/lib/planning/planner.js:93:55
    at Array.forEach (native)
    at _createSubRequests (/home/igor/psb/node_modules/inversify/lib/planning/planner.js:84:24)
    at Object.plan (/home/igor/psb/node_modules/inversify/lib/planning/planner.js:116:5)
    at /home/igor/psb/node_modules/inversify/lib/container/container.js:191:37
    at Container._get (/home/igor/psb/node_modules/inversify/lib/container/container.js:184:44)
    at Container.get (/home/igor/psb/node_modules/inversify/lib/container/container.js:149:21)
```

**Comment by remojansen** [comment]
There is no way to catch this at compilation time but I have added a validation check that will be included in the release.

It will throw the following:

> The toSelf function can only be applied when a constructor is used as service identifier
