### ISSUE TITLE
Can't read property name of undefined

### ISSUE THREAD

**Issue by abarmawi** [inversify/InversifyJS#584]
this my stack trace

```
Error: Cannot read property 'name' of undefined
    at _createSubRequests (/Users/abarmawi/Desktop/My Files/MyProjects/Platform/Service/node_modules/inversify/lib/planning/planner.js:107:19)
    at Object.plan (/Users/abarmawi/Desktop/My Files/MyProjects/Platform/Service/node_modules/inversify/lib/planning/planner.js:126:5)
    at Container._planAndResolve (/Users/abarmawi/Desktop/My Files/MyProjects/Platform/Service/node_modules/inversify/lib/container/container.js:228:37)
    at Container._get (/Users/abarmawi/Desktop/My Files/MyProjects/Platform/Service/node_modules/inversify/lib/container/container.js:221:44)
    at Container.get (/Users/abarmawi/Desktop/My Files/MyProjects/Platform/Service/node_modules/inversify/lib/container/container.js:180:21)
    at Object.<anonymous> (/Users/abarmawi/Desktop/My Files/MyProjects/Platform/Service/dist/Server.js:154:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

and below is my implementation 

```ts
import "reflect-metadata";

// define app types
let TYPES = {
    IServer: Symbol("IServer"),
    // IAuthentication: Symbol("IAuthentication")
};

export { TYPES };`
```

```ts
import "reflect-metadata";
import { Container } from "inversify";

// Import app dependencies
import { TYPES } from "./Types";
import { IAuthentication, PassportStrategies } from "../../AuthenticationLayer/V1";
import { IServer } from "../../IServer";
import { Server } from "../../Server";

var myContainer = new Container();
// myContainer.bind<IAuthentication>(TYPES.IAuthentication).to(PassportStrategies);
myContainer.bind<IServer>(TYPES.IServer).to(Server);

// Export module
export { myContainer };`
```

**Comment by remojansen** [comment]
We need more details to be able to help, we need the code of the `Server` class and see how do you invoke `myContainer.get<IServer>(TYPES.IServer)`.

**Comment by abarmawi** [comment]
@remojansen 

this is my IServer 
`
interface IServer {
    bootstrap(): IServer;
}
export { IServer };
`

this is my Server
```

// Import npm dependencies
import * as bodyParser from "body-parser";
import * as cookieParser from "cookie-parser";
import * as express from "express";
import * as logger from "morgan";
import * as path from "path";
import errorHandler = require("errorhandler");
import methodOverride = require("method-override");
import "reflect-metadata";
import { injectable, inject } from "inversify";

// Import app dependencies
import { IndexRoute } from "../routes/indexRoute";
import { IAuthentication as IAuthenticationV1 } from "../AuthenticationLayer/V1/";
import { systemConfig as systemConfigV1 } from "../Config/V1";
import { TYPES, myContainer } from "../Helpers/IOC/InversifyJS/";
import { IServer } from "./IServer";


/**
 * The server.
 *
 * @class Server
 */
@injectable()
class Server implements IServer {

    public app: express.Application;

  
    private iAuthentication: IAuthenticationV1;

    /**
     * Bootstrap the application.
     *
     * @class Server
     * @method bootstrap
     * @return {ng.auto.IInjectorService} Returns the newly created injector for this app.
     */
    public bootstrap(): Server {
        return new Server();
    }

    /**
     * Constructor.
     *
     * @class Server
     * @constructor
     */
    constructor() {

        // create expressjs application
        this.app = express();

        // configure application
        this.config();

        // add routes
        this.routes();

        // add api
        this.api();

        // start web server
        this.start();
    }

    /**
     * Create REST API routes
     *
     * @class Server
     * @method api
     */
    public api() {
        // empty for now
    }

    /**
     * Configure application
     *
     * @class Server
     * @method config
     */
    public config() {
        // add static paths
        // this.app.use(express.static(path.join(__dirname, "public")));

        // configure pug
        // this.app.set("views", path.join(__dirname, "views"));
        // this.app.set("view engine", "pug");

        // use logger middleware
        this.app.use(logger("dev"));

        // use json form parser middleware
        this.app.use(bodyParser.json());

        // use query string parser middleware
        this.app.use(bodyParser.urlencoded({
            extended: true
        }));

        // build & configure auth process.
        this.iAuthentication.configure(this.app);

        // use cookie parker middleware middleware
        this.app.use(cookieParser("SECRET_GOES_HERE"));

        // use override middleware
        this.app.use(methodOverride());

        // catch 404 and forward to error handler
        // this.app.use(function (err: any, req: express.Request, res: express.Response, next: express.NextFunction) {
        //     err.status = 404;
        //     next(err);
        // });

        // error handling
        this.app.use(errorHandler());
    }

    /**
     * Create router
     *
     * @class Server
     * @method api
     */
    public routes() {
        let router: express.Router;
        router = express.Router();

        // IndexRoute
        IndexRoute.create(router);

        // use router middleware
        this.app.use(router);

        // catch any error and forward to error handler
        this.app.use((error: any, req: express.Request, res: express.Response, next: Function) => {

            console.log("test test test");
            console.log(error);

            res.status(500).json(error).end();
        });
    }

    /**
     * Starts web server on specific port.
     */
    public start(): void {

        const port = systemConfigV1.SystemConfig().API.PORT();

        this.app.listen(port, (error: any) => {
            if (error) {
                console.log(`can't start server. error : ${error}`);
            }
            else {
                console.log(`Server started on port ${port}`);
            }

        });
    }
}

// Export module
export { Server };



```

and this is how i call 
```

try {
    // start the server.
     let server = myContainer.get<IServer>(TYPES.IServer);

    
} catch (error) {
    console.log("An error occurred while boot strapping app.");
    throw error;
}

```

**Comment by abarmawi** [comment]
@remojansen 

it's working fine now

the only thing i did is just install "inversify-inject-decorators", the every thing works fine.
then i uninstalled it "inversify-inject-decorators" but every thing works find!!!

any explanation?
