### ISSUE TITLE
middleware class injection failing with inversify-express-utils

### ISSUE THREAD

**Issue by veeramarni** [inversify/InversifyJS#638]
I was trying to inject middleware class in `controller` class as below.  And I'm getting below stack errror. Is it something wrong with my setup?

Controller
---
```
@controller('/oauth')
@injectable()
export class OAuthController implements interfaces.Controller {

    constructor(
        @inject(ServerTypes.ITokenizeMiddleware) private tokenize: AbstractMiddleware,
        @multiInject(ServerTypes.IOAuthProvider) private providers: Array<AbstractProvider>,
    ) {
    }

    @httpGet('/process/:provider', this.tokenize.exec.bind(this))
    public authenticate(req, res, next) {
        const strategy: AbstractProvider = this.providers.find(provider => req.params.provider === provider.name);
        Passport.authenticate(strategy.name, Object.assign({
            ...strategy.arguments,
            state: req.token,
        }, strategy.modify({ token: req.token })))(req, res, next);
    }
```
Middleware
---
```
@injectable()
export class TokenizeMiddleware extends AbstractMiddleware {
    @inject(TYPES.IJWTService) public jwt: JWTService;
    @inject(TYPES.IAccountsServerConfiguration) public settings: IAccountsServerConfiguration;

    public exec(req: any, res: any, next: any) {
        const { redirect_host, protocol, response_type = 'code' } = req.query;
        let { redirect_uri = ''} = req.query;
        if (!redirect_uri) {
            redirect_uri = format({ host: redirect_host, protocol});
        }
        req.token = this.jwt.encode({
            response_type,
            callbackUrl: redirect_uri || this.settings.auth.callback || false,
            provider: req.params.provider || req.query.provider,
        });

        next();
    }
}

```
Module to load later
---
```
export const IdentityExpressModule = new ContainerModule((bind) => {

    registerController(bind, OAuthController);
});
```
## Expected Behavior
It should able to go through the middleware without throwing any error. 

## Your Environment

* Version used: Inversify:  4.1.0, inversify-express-utils: 4.0.1
* Environment name and version (e.g. Chrome 39, node.js 5.4):node.js 8.4.0
* Operating System and version (desktop or mobile): mac os

# Stack trace

   inversify_express_utils_1.httpGet('/process/:provider', this.tokenize.exec.bind(this))
                                                                         ^
```
TypeError: Cannot read property 'exec' of undefined
    at Object.__dirname../packages/identity-express-module/lib/index.js.module.exports.Object.defineProperty.value (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/identity-stack/servers/backend-server/dist/index.js:967:74)
    at __webpack_require__ (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/identity-stack/servers/backend-server/dist/index.js:801:30)
    at Object.<anonymous> (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/identity-stack/servers/backend-server/dist/index.js:860:10)
    at __webpack_require__ (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/identity-stack/servers/backend-server/dist/index.js:801:30)
    at Object.<anonymous> (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/identity-stack/servers/backend-server/dist/index.js:1007:10)
    at __webpack_require__ (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/identity-stack/servers/backend-server/dist/index.js:801:30)
    at __dirname../packages/identity-express-module/lib/index.js.module.exports.Object.defineProperty.value (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/identity-stack/servers/backend-server/dist/index.js:847:18)
    at Object../packages/identity-express-module/lib/index.js (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/identity-stack/servers/backend-server/dist/index.js:850:10)
```

**Comment by veeramarni** [comment]
I have noticed this is something not yet added to the feature. Only `ServiceIdentifier` or `RequestHanlder` functions are only workable based on #487

**Comment by veeramarni** [comment]
Further I have tried the following.

Injecting middleware
----
```
container.bind<interfaces.Middleware>(IdentityTypes.ITokenizeMiddleware).toDynamicValue((context: coreInterfaces.Context) => {
    let jwt = context.container.get<JWTService>(IdentityTypes.IJWTService);
    let settings = context.container.get<IAccountsServerConfiguration>(IdentityTypes.IAccountsServerConfiguration);
    let logger: Logger = context.container.get<Logger>('Logger');
    return TokenizeMiddlewareFactory(jwt, settings, logger);
});
```

Controller
---
```
@controller('/oauth')
@injectable()
export class OAuthController implements interfaces.Controller {

    constructor(
        @inject(ServerTypes.IJWTService) private jwt: JWTService,
        @multiInject(ServerTypes.IOAuthProvider) private providers: Array<AbstractProvider>,
    ) {
    }

    @httpGet('/process/:provider',  ServerTypes.ITokenizeMiddleware)
    public authenticate(req, res, next) {
        const strategy: AbstractProvider = this.providers.find(provider => req.params.provider === provider.name);
        Passport.authenticate(strategy.name, Object.assign({
            ...strategy.arguments,
            state: req.token,
        }, strategy.modify({ token: req.token })))(req, res, next);
    }
```

I don't think `injections` is working for `middleware` as I'm seeing below errors. 

```
TypeError: Cannot read property 'debug' of undefined
    at servers/packages/identity-server-core/lib/index.js:832:1

```

**Comment by veeramarni** [comment]
Tried as per #487, I think i can skip this issue.
