### ISSUE TITLE
Missing required @injectable annotation in: Anonymous function: function (target)

### ISSUE THREAD

**Issue by mnifakram** [inversify/InversifyJS#741]
I'm not sure whether this is related to #297, #262, #524 but all of them got this issue as a result of an inheritance. 

I was trying to integrate `inversify-inject-decorators`  to be able to call the constructor but the property doesn't get injected properly (if I did understand the error message well).

Can you please tell me what I'm doing wrong? 
https://github.com/mnifakram/inversify-issue
or if you have c9 account => https://ide.c9.io/akrammnif/ioc-test

Stack trace
```
/home/ubuntu/workspace/node_modules/inversify/lib/planning/reflection_utils.js:19
        throw new Error(msg);
              ^
Error: Missing required @injectable annotation in: Anonymous function: function (target) {
        if (Reflect.hasOwnMetadata(METADATA_KEY.PARAM_TYPES, target)) {
            throw new Error(ERRORS_MSGS.DUPLICATED_INJECTABLE_DECORATOR);
        }
        var types = Reflect.getMetadata(METADATA_KEY.DESIGN_PARAM_TYPES, target) || [];
        Reflect.defineMetadata(METADATA_KEY.PARAM_TYPES, types, target);
        return target;
    }.
    at getTargets (/home/ubuntu/workspace/node_modules/inversify/lib/planning/reflection_utils.js:19:15)
    at Object.getDependencies (/home/ubuntu/workspace/node_modules/inversify/lib/planning/reflection_utils.js:10:19)
    at /home/ubuntu/workspace/node_modules/inversify/lib/planning/planner.js:106:51
    at Array.forEach (native)
    at _createSubRequests (/home/ubuntu/workspace/node_modules/inversify/lib/planning/planner.js:94:20)
    at Object.plan (/home/ubuntu/workspace/node_modules/inversify/lib/planning/planner.js:129:9)
    at /home/ubuntu/workspace/node_modules/inversify/lib/container/container.js:243:37
    at Container._get (/home/ubuntu/workspace/node_modules/inversify/lib/container/container.js:236:44)
    at Container.get (/home/ubuntu/workspace/node_modules/inversify/lib/container/container.js:195:21)
    at resolve (/home/ubuntu/workspace/node_modules/inversify-inject-decorators/lib/decorators.js:25:34)
```

**Comment by mnifakram** [comment]
sorry it was my mistake used `@injectable` instead of `@injectable()`
