### ISSUE TITLE
[ERR_ASSERTION]: Constructor already exists! (restify@7.1.1 + inversify-restify-utils@3.3.1)

### ISSUE THREAD

**Issue by hlibco** [inversify/InversifyJS#847]
Similar to the closed issue #703 (but with a newer version of **restify**)

## Expected Behavior
It should start the `restify` server without problems.

## Current Behavior
As soon as `restify` is imported an error is thrown: `[ERR_ASSERTION]: Constructor already exists!`

## Possible Solution
To use `inversify-restify-utils@3.3.1` I had to downgrade Restify to `restify@6.3.2`

## Steps to Reproduce (for bugs)
Clone the following repo: [https://github.com/hlibco/restify-inversify-constructor-error](https://github.com/hlibco/restify-inversify-constructor-error)

1. install dependencies `yarn install` or `npm install`
2. run `yarn start` or `npm start`
3. you should get the error

```
node_modules/restify-errors/lib/index.js:67
    assert.equal(typeof module.exports[name], 'undefined',
           ^
AssertionError [ERR_ASSERTION]: Constructor already exists!
```

## Your Environment
- node v9.4.0

```
    "inversify": "4.11.1",
    "inversify-restify-utils": "3.3.1",
    "reflect-metadata": "^0.1.12",
    "restify": "7.1.1",
```

# Stack trace
```
/Users/earth/git-public/restify-inversify-problem/node_modules/restify-errors/lib/index.js:67
    assert.equal(typeof module.exports[name], 'undefined',
           ^
AssertionError [ERR_ASSERTION]: Constructor already exists!
    at Object.makeConstructor (/Users/earth/git-public/restify-inversify-problem/node_modules/restify-errors/lib/index.js:67:12)
    at Object.<anonymous> (/Users/earth/git-public/restify-inversify-problem/node_modules/restify/lib/errorTypes.js:5:8)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/earth/git-public/restify-inversify-problem/node_modules/restify/lib/index.js:14:1)
```

**Comment by hlibco** [comment]
Hi @remojansen I saw you closed the issue #703 (similar to the one I just opened) by suggesting to upgrade to `restify@6.3.4`. It didn't work to be (but 6.3.2 did). However, upgrading to `restify@7.1.1` (latest - at the time of this post), the error persists.

Any idea of how `inversify-restify-utils` users should proceed?

**Comment by hlibco** [comment]
The `inversify-restify-utils` on github has its dependencies being updated by `greenkeeper`. That's great. It would be even better if the up-to-date version on github could be published to NPM. It would fix the #847

I manually changed the version of `restify` which `inversify-resity-utils` dependends on (from 6.3.2 to 7.1.1) and it fixed the issue.

**Comment by mgebundy** [comment]
I'm also blocked upgrading to the most recent versions of Inversify and Restify by this. Could a new version be published to npm? That would be incredibly helpful.

**Comment by jinghualin** [comment]
I resolved this problem in current version
 - restify@7.2.1
 - inversify@4.13.0
 - inversify-restify-utils@3.3.1
 - typescript@2.9.1
with manually install restify-errors.

From restify version 6 I have same problem, when I do not install the restify-errors module.

**Comment by mgebundy** [comment]
@hlibco `inversify-restify-utils` has been updated, the new `v3.4` should be compatible with the most recent version of inversity and restify v7

**Comment by notaphplover** [comment]
Restify utils have been archived
