### ISSUE TITLE
inversify-restify-utils tests are failing on master

### ISSUE THREAD

**Issue by mgebundy** [inversify/InversifyJS#886]
## Expected Behavior
The `inversify-restify-utils` test suite should pass

## Current Behavior
Some `inversify-restify-utils` tests are failing. All the `greenkeeper` PRs are as well, even when they are seen as "passed"

```
  11 passing (305ms)
  4 failing

  1) Integration Tests:
       Routing & Request Handling:
         should allow server options with defaultRoot:
     Error: expected 200 "OK", got 404 "Not Found"
      at Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1671:8)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  2) Integration Tests:
       Middleware:
         "before each" hook for "should call method-level middleware correctly":
     TypeError: spyA.reset is not a function
      at Context.<anonymous> (test/framework.test.js:286:18)

  3) Unit Test: InversifyRestifyServer
       should generate routes for controller methods:
     TypeError: Cannot read property 'GET' of undefined
      at Context.<anonymous> (test/server.test.js:73:42)

  4) Unit Test: InversifyRestifyServer
       should generate routes for controller methods using defaultRoot:
     TypeError: Cannot read property 'GET' of undefined
      at Context.<anonymous> (test/server.test.js:118:42)
```

## Steps to Reproduce (for bugs)
1. Pull master on `inversify-restify-utils`
2. Run `npm i`
3. Run `npm test`

## Context
Most recent tag on utils is incompatible with the most recent versions of inversify and restify. I was hoping that I could pull down master and build it myself, but alas, that doesn't seem to be a reliable solution at all.

## Your Environment
Node v8.10.0
Npm 6.0.1

**Comment by notaphplover** [comment]
Restify utils have been archived
