### ISSUE TITLE
`redirect` method of BaseController doesn't work with inversify server.

### ISSUE THREAD

**Issue by Rokt33r** [inversify/InversifyJS#964]
## Expected Behavior
It should redirect page properly

## Current Behavior
It throws an error

```
TypeError: Cannot read property 'headers' of undefined
    at InversifyExpressServer.<anonymous> (/Users/junyoung/Code/issuehunt/node_modules/inversify-express-utils/lib/server.js:201:60)
    at step (/Users/junyoung/Code/issuehunt/node_modules/inversify-express-utils/lib/server.js:32:23)
    at Object.next (/Users/junyoung/Code/issuehunt/node_modules/inversify-express-utils/lib/server.js:13:53)
    at /Users/junyoung/Code/issuehunt/node_modules/inversify-express-utils/lib/server.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/junyoung/Code/issuehunt/node_modules/inversify-express-utils/lib/server.js:3:12)
    at InversifyExpressServer.handleHttpResponseMessage (/Users/junyoung/Code/issuehunt/node_modules/inversify-express-utils/lib/server.js:195:16)
    at InversifyExpressServer.<anonymous> (/Users/junyoung/Code/issuehunt/node_modules/inversify-express-utils/lib/server.js:242:51)
    at step (/Users/junyoung/Code/issuehunt/node_modules/inversify-express-utils/lib/server.js:32:23)
    at Object.next (/Users/junyoung/Code/issuehunt/node_modules/inversify-express-utils/lib/server.js:13:53)
    at fulfilled (/Users/junyoung/Code/issuehunt/node_modules/inversify-express-utils/lib/server.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

## Possible Solution

I made a temporary fix, which works on production and testing, by overriding redirect method.

```ts
redirect (target: string) {
    if (this.httpContext == null) return super.redirect(target)
    this.httpContext.response.redirect(target)
    return undefined as any
  }
```

## Steps to Reproduce (for bugs)

1. extend controller with BaseController
2. return `this.redirect('http://someurl...')`

## Your Environment

* Version used: inversify-express-utils@6.1.0
* express version: express@4.16.2

**Comment by dcavanagh** [comment]
fixed in version 6.2.0 which was just released. sorry for the delay
